// console.log is used to log (print) a message to the console.

// console.log("Hello World!");
// console.log("JavaScript");

// fullname = "Shubham";   
// age = 20;
// x = null;
// y = undefined;
// console.log(fullname);
// console.log(x);
// console.log(y);
// console.log(age);


// fullname = "Shubham";
// fullName = "Saumya";

// console.log(fullname);
// console.log(fullName);
// { 
//     let fullName = "Shubham";
//     let age = 20;
//     let totalPriced = 1000;
//     console.log(fullName, age, totalPriced);
// }

// {

//     const PI = 30.14;
//     console.log(PI);
// }

// let x = BigInt("123");

const student = {
    fullName : "Shubham",
    age : 20,
    cgpa : 10,
    isPass: true,
};

 student["age"] = student["age"] + 1;
// console.log(student.age, student.cgpa, student.isPass, student.fullName); not use [] if we are using .
console.log(student.age);
